plugin:
  backend: go-plugin
  go-plugin:
    dir: ../../../scheme/bin/
po-store:
  backend: sql
  sql:
    driver: sqlite3
    datasource: /tmp/po-store.sql
management:
  listen-addr: 0.0.0.0:10443
  protocol: https
  cert: ../../../deployments/docker/src/certs/management.crt
  cert-key: ../../../deployments/docker/src/certs/management.key
po-agent:
  backend: opa
logging:
  level: debug
auth:
  backend: keycloak
  host: localhost
  port: 11111
  realm: veraison
